"""
KAVACH — Report Model
Mirrors the report metadata generated by app/services/reports/report_generator.py
and app/tasks/report_tasks.py.

A row is created in "pending" status the moment a scan finishes
aggregating (before any report has actually been rendered), then updated
in place as `report_tasks.generate_reports_task` produces each artifact —
see `status` below. This is what makes report generation observably
asynchronous: `GET /reports/{scan_job_id}` can distinguish "still
generating" from "failed" from "ready to download" instead of only ever
seeing rows that already represent finished files.
"""

import uuid
from typing import TYPE_CHECKING, Optional

from sqlalchemy import ForeignKey, String, Text, UniqueConstraint
from sqlalchemy.dialects.postgresql import UUID
from sqlalchemy.orm import Mapped, mapped_column, relationship

from app.db.base import Base
from app.db.mixins import TimestampMixin, UUIDPrimaryKeyMixin

if TYPE_CHECKING:
    from app.models.scan_job import ScanJob

# pdf | pdf_technical | sarif | sbom | unified_findings | compliance_report | csv
REPORT_TYPE_MAX_LENGTH = 32

# pending -> generating -> completed | failed
REPORT_STATUS_MAX_LENGTH = 16


class Report(UUIDPrimaryKeyMixin, TimestampMixin, Base):
    __tablename__ = "reports"
    __table_args__ = (
        # One row per (scan job, report type) — generation is re-tried by
        # updating this row in place, never by inserting a second one.
        UniqueConstraint("scan_job_id", "report_type", name="uq_reports_scan_job_id_report_type"),
    )

    scan_job_id: Mapped[uuid.UUID] = mapped_column(
        UUID(as_uuid=True), ForeignKey("scan_jobs.id", ondelete="CASCADE"), nullable=False, index=True
    )
    report_type: Mapped[str] = mapped_column(String(REPORT_TYPE_MAX_LENGTH), nullable=False)
    status: Mapped[str] = mapped_column(String(REPORT_STATUS_MAX_LENGTH), nullable=False, default="pending")

    # Nullable — unset until generation actually completes.
    file_path: Mapped[Optional[str]] = mapped_column(String(1024), nullable=True)
    # "local" | "s3" — which backend `file_path`/`storage_key` should be read through.
    storage_backend: Mapped[str] = mapped_column(String(16), nullable=False, default="local")
    # The S3 object key when storage_backend == "s3"; unused for "local"
    # (local reads go through file_path directly).
    storage_key: Mapped[Optional[str]] = mapped_column(String(1024), nullable=True)

    error_message: Mapped[Optional[str]] = mapped_column(Text, nullable=True)

    scan_job: Mapped["ScanJob"] = relationship(back_populates="reports")
